package com.example.locations

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

// Defines the LocationData entity, represents a table within the database.
@Entity(tableName = "location_data")
data class LocationData(

    // Primary key for the entity, auto generated by Room.
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    // Represents the location data.
    val location: String,

    // Represents the name of the location.
    val text: String  ,

    // Represents the azimuth data.
    val azimuth: String
)

